"""initial schema

Revision ID: b3c4b22cde0d
Revises: 
Create Date: 2026-08-24 12:07:32.370982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3c4b22cde0d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=600), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_path')
    )
    op.create_index(op.f('ix_attachments_entity_id'), 'attachments', ['entity_id'], unique=False)
    op.create_index(op.f('ix_attachments_entity_type'), 'attachments', ['entity_type'], unique=False)
    op.create_index(op.f('ix_attachments_sha256'), 'attachments', ['sha256'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_type'), 'audit_events', ['entity_type'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('contact', sa.String(length=200), nullable=True),
    sa.Column('bank_information', sa.Text(), nullable=True),
    sa.Column('cheque_information', sa.Text(), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('logo_path', sa.String(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_companies_code'), 'companies', ['code'], unique=True)
    op.create_table('export_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('export_type', sa.String(length=30), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('stored_path', sa.String(length=600), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_records_entity_id'), 'export_records', ['entity_id'], unique=False)
    op.create_index(op.f('ix_export_records_export_type'), 'export_records', ['export_type'], unique=False)
    op.create_table('platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('trustee', sa.String(length=250), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('fcs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_fc_company_code')
    )
    op.create_index(op.f('ix_fcs_company_id'), 'fcs', ['company_id'], unique=False)
    op.create_table('fee_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('fee_rate_bps', sa.Integer(), nullable=False),
    sa.Column('calculation_method', sa.String(length=80), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_fee_plan_company_code')
    )
    op.create_index(op.f('ix_fee_plans_company_id'), 'fee_plans', ['company_id'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('fc_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact', sa.String(length=250), nullable=True),
    sa.Column('management_start_date', sa.Date(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fc_id'], ['fcs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_company_id'), 'clients', ['company_id'], unique=False)
    op.create_index(op.f('ix_clients_fc_id'), 'clients', ['fc_id'], unique=False)
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=False)
    op.create_index(op.f('ix_clients_status'), 'clients', ['status'], unique=False)
    op.create_table('invoice_sequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fc_id', sa.Integer(), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fc_id'], ['fcs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'fc_id', name='uq_invoice_sequence_company_fc')
    )
    op.create_table('quarterly_settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('fee_plan_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('closing_date', sa.Date(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('beginning_cents', sa.Integer(), nullable=False),
    sa.Column('contribution_cents', sa.Integer(), nullable=False),
    sa.Column('withdrawal_cents', sa.Integer(), nullable=False),
    sa.Column('net_contribution_cents', sa.Integer(), nullable=False),
    sa.Column('closing_cents', sa.Integer(), nullable=False),
    sa.Column('gain_loss_cents', sa.Integer(), nullable=False),
    sa.Column('period_rate_ppm', sa.Integer(), nullable=True),
    sa.Column('original_hwm_cents', sa.Integer(), nullable=False),
    sa.Column('adjusted_hwm_cents', sa.Integer(), nullable=False),
    sa.Column('watermark_difference_cents', sa.Integer(), nullable=False),
    sa.Column('chargeable_above_hwm_cents', sa.Integer(), nullable=False),
    sa.Column('service_fee_cents', sa.Integer(), nullable=False),
    sa.Column('next_hwm_cents', sa.Integer(), nullable=False),
    sa.Column('fee_rate_bps', sa.Integer(), nullable=False),
    sa.Column('formula_version', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fee_plan_id'], ['fee_plans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'platform_id', 'fee_plan_id', 'year', 'quarter', name='uq_settlement_group_period')
    )
    op.create_index(op.f('ix_quarterly_settlements_client_id'), 'quarterly_settlements', ['client_id'], unique=False)
    op.create_index(op.f('ix_quarterly_settlements_fee_plan_id'), 'quarterly_settlements', ['fee_plan_id'], unique=False)
    op.create_index(op.f('ix_quarterly_settlements_platform_id'), 'quarterly_settlements', ['platform_id'], unique=False)
    op.create_index(op.f('ix_quarterly_settlements_quarter'), 'quarterly_settlements', ['quarter'], unique=False)
    op.create_index(op.f('ix_quarterly_settlements_status'), 'quarterly_settlements', ['status'], unique=False)
    op.create_index(op.f('ix_quarterly_settlements_year'), 'quarterly_settlements', ['year'], unique=False)
    op.create_table('sub_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.Column('fee_plan_id', sa.Integer(), nullable=True),
    sa.Column('account_number', sa.String(length=100), nullable=False),
    sa.Column('scheme_name', sa.String(length=250), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fee_plan_id'], ['fee_plans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_id', 'account_number', name='uq_platform_account')
    )
    op.create_index(op.f('ix_sub_accounts_account_number'), 'sub_accounts', ['account_number'], unique=False)
    op.create_index(op.f('ix_sub_accounts_client_id'), 'sub_accounts', ['client_id'], unique=False)
    op.create_index(op.f('ix_sub_accounts_fee_plan_id'), 'sub_accounts', ['fee_plan_id'], unique=False)
    op.create_index(op.f('ix_sub_accounts_platform_id'), 'sub_accounts', ['platform_id'], unique=False)
    op.create_index(op.f('ix_sub_accounts_status'), 'sub_accounts', ['status'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('settlement_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fc_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('lifecycle_status', sa.String(length=20), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('pdf_paths_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fc_id'], ['fcs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['settlement_id'], ['quarterly_settlements.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_company_id'), 'invoices', ['company_id'], unique=False)
    op.create_index(op.f('ix_invoices_fc_id'), 'invoices', ['fc_id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoices_lifecycle_status'), 'invoices', ['lifecycle_status'], unique=False)
    op.create_index(op.f('ix_invoices_settlement_id'), 'invoices', ['settlement_id'], unique=False)
    op.create_table('statement_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=600), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('parser_name', sa.String(length=80), nullable=False),
    sa.Column('parser_version', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('extracted_json', sa.JSON(), nullable=True),
    sa.Column('reviewed_json', sa.JSON(), nullable=True),
    sa.Column('revision_log_json', sa.JSON(), nullable=True),
    sa.Column('confidence_json', sa.JSON(), nullable=True),
    sa.Column('warnings_json', sa.JSON(), nullable=True),
    sa.Column('duplicate_of_id', sa.Integer(), nullable=True),
    sa.Column('confirmed_account_id', sa.Integer(), nullable=True),
    sa.Column('confirmed_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_account_id'], ['sub_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statement_imports_sha256'), 'statement_imports', ['sha256'], unique=True)
    op.create_index(op.f('ix_statement_imports_status'), 'statement_imports', ['status'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('attachment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['sub_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_date'), 'transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_type'), 'transactions', ['transaction_type'], unique=False)
    op.create_table('balance_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('total_balance_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('statement_import_id', sa.Integer(), nullable=True),
    sa.Column('holdings_json', sa.JSON(), nullable=True),
    sa.Column('eligible_for_closing', sa.Boolean(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['sub_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['statement_import_id'], ['statement_imports.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'as_of_date', name='uq_account_snapshot_date')
    )
    op.create_index(op.f('ix_balance_snapshots_account_id'), 'balance_snapshots', ['account_id'], unique=False)
    op.create_index(op.f('ix_balance_snapshots_as_of_date'), 'balance_snapshots', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_balance_snapshots_statement_import_id'), 'balance_snapshots', ['statement_import_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=80), nullable=False),
    sa.Column('proof_attachment_id', sa.Integer(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proof_attachment_id'], ['attachments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.create_table('settlement_account_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('settlement_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('beginning_cents', sa.Integer(), nullable=False),
    sa.Column('closing_cents', sa.Integer(), nullable=False),
    sa.Column('closing_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['sub_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['closing_snapshot_id'], ['balance_snapshots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['settlement_id'], ['quarterly_settlements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('settlement_id', 'account_id', name='uq_settlement_account')
    )
    op.create_index(op.f('ix_settlement_account_lines_account_id'), 'settlement_account_lines', ['account_id'], unique=False)
    op.create_index(op.f('ix_settlement_account_lines_settlement_id'), 'settlement_account_lines', ['settlement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settlement_account_lines_settlement_id'), table_name='settlement_account_lines')
    op.drop_index(op.f('ix_settlement_account_lines_account_id'), table_name='settlement_account_lines')
    op.drop_table('settlement_account_lines')
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_balance_snapshots_statement_import_id'), table_name='balance_snapshots')
    op.drop_index(op.f('ix_balance_snapshots_as_of_date'), table_name='balance_snapshots')
    op.drop_index(op.f('ix_balance_snapshots_account_id'), table_name='balance_snapshots')
    op.drop_table('balance_snapshots')
    op.drop_index(op.f('ix_transactions_transaction_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_statement_imports_status'), table_name='statement_imports')
    op.drop_index(op.f('ix_statement_imports_sha256'), table_name='statement_imports')
    op.drop_table('statement_imports')
    op.drop_index(op.f('ix_invoices_settlement_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_lifecycle_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_fc_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_company_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_sub_accounts_status'), table_name='sub_accounts')
    op.drop_index(op.f('ix_sub_accounts_platform_id'), table_name='sub_accounts')
    op.drop_index(op.f('ix_sub_accounts_fee_plan_id'), table_name='sub_accounts')
    op.drop_index(op.f('ix_sub_accounts_client_id'), table_name='sub_accounts')
    op.drop_index(op.f('ix_sub_accounts_account_number'), table_name='sub_accounts')
    op.drop_table('sub_accounts')
    op.drop_index(op.f('ix_quarterly_settlements_year'), table_name='quarterly_settlements')
    op.drop_index(op.f('ix_quarterly_settlements_status'), table_name='quarterly_settlements')
    op.drop_index(op.f('ix_quarterly_settlements_quarter'), table_name='quarterly_settlements')
    op.drop_index(op.f('ix_quarterly_settlements_platform_id'), table_name='quarterly_settlements')
    op.drop_index(op.f('ix_quarterly_settlements_fee_plan_id'), table_name='quarterly_settlements')
    op.drop_index(op.f('ix_quarterly_settlements_client_id'), table_name='quarterly_settlements')
    op.drop_table('quarterly_settlements')
    op.drop_table('invoice_sequences')
    op.drop_index(op.f('ix_clients_status'), table_name='clients')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_fc_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_company_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_fee_plans_company_id'), table_name='fee_plans')
    op.drop_table('fee_plans')
    op.drop_index(op.f('ix_fcs_company_id'), table_name='fcs')
    op.drop_table('fcs')
    op.drop_table('platforms')
    op.drop_index(op.f('ix_export_records_export_type'), table_name='export_records')
    op.drop_index(op.f('ix_export_records_entity_id'), table_name='export_records')
    op.drop_table('export_records')
    op.drop_index(op.f('ix_companies_code'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_audit_events_entity_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_attachments_sha256'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_entity_type'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_entity_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
